FROM node:24.1.0-alpine AS development

ENV NODE_ENV development

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . . 
# mount /src to /app/src for editting frontend for hot reload

CMD ["npm","start"]