FROM python:3.12-slim

WORKDIR /app


COPY main.py .
COPY requirements.txt .

COPY model/decisionTree_sleep_risk_classifier ./model/

RUN pip install --no-cache-dir --upgrade -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]