worker_processes 1;

events {
    worker_connections 1024;  # Minimum required
}

http {

    # General API rate limit (per IP)
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=3r/s;

    # Stricter limit for ML endpoint
    limit_req_zone $binary_remote_addr zone=ml_limit:10m rate=1r/s;

    server {
        listen 80;

        # FRONTEND (React on port 3000)
        location = / {
            proxy_pass http://host.docker.internal:3000;
            proxy_set_header Host $host;
        }

        # GENERAL API
        location = /api/ {
            proxy_pass http://ml_backend:8000/;

            limit_req zone=api_limit burst=5 nodelay;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ML API
        location = /api/disorder_risk_inference {

            # allow preflight
            if ($request_method = OPTIONS ) {
                add_header Access-Control-Allow-Origin *;
                add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
                add_header Access-Control-Allow-Headers "Content-Type, Authorization";
                return 204;
            }

            proxy_pass http://ml_backend:8000/disorder_risk_inference;

            limit_req zone=ml_limit burst=1 nodelay;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}